# Generated by Django 3.0.8 on 2020-12-07 19:40

from django.db import migrations, models
import django.db.models.deletion
import shop2.files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shop2.files.models.FilesStorage),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelFiles',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner', models.UUIDField(default=uuid.uuid4)),
                ('cloud_link', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, default='Файл', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='Описания нет', max_length=1000)),
                ('unit_of_measurement', models.CharField(max_length=15)),
                ('view_in_catalog', models.BooleanField(default=False)),
                ('details', models.ManyToManyField(to='shop2.Detail')),
                ('products_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shop2.files.models.FilesStorage),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(max_length=50)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop2.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='detail_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.DetailGroup'),
        )
    ]
