# Generated by Django 3.0.8 on 2020-12-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='products_category',
        ),
    ]
