# Generated by Django 3.0.8 on 2020-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
