# Generated by Django 3.0.8 on 2020-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_auto_20201202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail_group',
            field=models.ForeignKey(db_column='detail_group', on_delete=django.db.models.deletion.CASCADE, to='shop2.DetailGroup'),
        ),
    ]
