# Generated by Django 3.0.8 on 2020-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0003_auto_20201202_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='product',
        ),
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
