# Generated by Django 3.0.8 on 2020-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0003_balance_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
