# Generated by Django 3.0.8 on 2020-12-02 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0004_auto_20201202_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.DetailGroup'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
