# Generated by Django 3.0.8 on 2020-12-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0004_auto_20201207_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='products_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop2.Category'),
        ),
    ]
