# Generated by Django 3.0.8 on 2020-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0005_auto_20201202_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(to='shop2.Detail'),
        ),
    ]
