# Generated by Django 3.0.8 on 2020-12-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0005_auto_20201209_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sorting',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
