# Generated by Django 3.0.8 on 2020-12-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0006_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_in_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
