# Generated by Django 3.0.8 on 2020-12-04 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0007_product_view_in_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFiles',
            fields=[
                ('marked_to_delete', models.BooleanField(default=False)),
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner', models.UUIDField(default=uuid.uuid4)),
                ('cloud_link', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, default='Файл', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
