# Generated by Django 3.0.8 on 2020-09-02 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('parent', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFiles',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner', models.UUIDField(default=uuid.uuid4)),
                ('cloud_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_of_measurement', models.CharField(default=None, max_length=10)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category')),
                ('detail', models.ManyToManyField(blank=True, to='shop.Detail')),
                ('files', models.ManyToManyField(blank=True, to='shop.ModelFiles')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='detail_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.DetailGroup'),
        ),
    ]
