# Generated by Django 3.0.8 on 2020-07-15 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_of_measurement', models.CharField(default=None, max_length=10)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('detail', models.ManyToManyField(to='shop.Detail')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='detail_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.DetailGroup'),
        ),
    ]
