# Generated by Django 3.0.8 on 2020-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='detailgroup',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
