# Generated by Django 3.0.8 on 2020-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfiles',
            name='title',
            field=models.CharField(default='Файл', max_length=100),
        ),
    ]
