# Generated by Django 3.0.8 on 2020-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_modelfiles_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.AlterField(
            model_name='modelfiles',
            name='title',
            field=models.CharField(blank=True, default='Файл', max_length=100),
        ),
    ]
