# Generated by Django 3.0.8 on 2020-07-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(to='shop.ChildCategory'),
        ),
    ]
