# Generated by Django 3.0.8 on 2020-09-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200907_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='car_type',
            new_name='client_type',
        ),
    ]
