# Generated by Django 3.0.8 on 2020-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200717_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, to='shop.ChildCategory'),
        ),
    ]
