# Generated by Django 3.0.8 on 2020-07-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200717_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, to='shop.ParentCategory'),
        ),
    ]
