# Generated by Django 3.0.8 on 2020-09-22 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_detail_active_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.UUIDField(default=uuid.uuid4)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('product_length', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('product_quantity', models.IntegerField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, null=True)),
            ],
        ),
    ]
