# Generated by Django 3.0.8 on 2020-07-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200717_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='children',
            new_name='parents',
        ),
    ]
