# Generated by Django 3.0.8 on 2020-07-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200717_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(to='shop.Category'),
        ),
        migrations.DeleteModel(
            name='ParentCategory',
        ),
    ]
