# Generated by Django 3.0.8 on 2020-09-22 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200922_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
