# Generated by Django 3.0.8 on 2020-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200717_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ManyToManyField(blank=True, to='shop.Category'),
        ),
    ]
