# Generated by Django 3.0.8 on 2020-07-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200717_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(to='shop.ChildrenCategory'),
        ),
    ]
