# Generated by Django 3.0.8 on 2020-10-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201005_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sotring', models.IntegerField(blank=True, default=1, max_length=10000)),
                ('answer', models.CharField(max_length=4000)),
                ('question', models.CharField(max_length=300)),
            ],
        ),
    ]
