# Generated by Django 3.0.8 on 2020-07-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200717_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.DeleteModel(
            name='ChildrenCategory',
        ),
    ]
