# Generated by Django 3.0.8 on 2020-10-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('sorting',)},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='sotring',
            new_name='sorting',
        ),
    ]
