# Generated by Django 3.0.8 on 2020-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201012_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailgroup',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detailgroup',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelfiles',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelfiles',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='active_object',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sorting',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
