# Generated by Django 3.0.8 on 2020-07-21 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200721_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
