# Generated by Django 3.0.8 on 2020-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200721_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.UUIDField(blank=True, default='00000000-0000-0000-0000-000000000000'),
        ),
    ]
