# Generated by Django 3.0.8 on 2020-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200721_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
