# Generated by Django 3.0.8 on 2020-07-21 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200721_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
